### ISSUE TITLE
Doesn't work any more after the update

### ISSUE THREAD

**Issue by cremor** [sorz/accept-language-per-site#11]
After one of the updates that was released last week or today the addon stopped working. It worked fine last year. Now it doesn't work any more and I didn't change any settings. It simply doesn't change the Accept-Language header any more.

There are similar problem reports in the comments of the addon on addons.mozilla.org

I've tried adding a new rule but that also doesn't work.

Here are my rules:
![grafik](https://github.com/sorz/accept-language-per-site/assets/116314/25970dd9-3016-471e-863f-62914b48b1e9)

Addon version 0.3.2
Firefox version 121.0 on Windows 10

**Comment by sorz** [comment]
Wildcard subdomains did not work on v0.3.0 and v0.3.1. But it should have been fix since v0.3.2 (#10).

Did you use, for example, `*.a-trust.at` to match `a-trust.at`? This behavior has been changed to that the wildcard will match all subdomains but not the top-level domain itself. So it now require two separated rules, `*.a-trust.at` and `a-trust.at`, to achieve the old effect.

This behavior change is sole due to my convenient of programming during MV3 API migration. But it seems causing lots of confusion. I'm considering bring back the old behavior.

**Comment by sorz** [comment]
Just released v0.3.3, can you try it?

**Comment by cremor** [comment]
I've updated to 0.3.3 and now the header is correctly sent again for the main HTTP request. But some sites are still shown in english (my browser default) for me even though they were shown in the language configured in your addon before the addon update.

I assume this is because subsequent requests like the ones for scripts and images are still sent with the default language header, even though they would match the rule. One example site is https://www.chargeprice.app

**Comment by sorz** [comment]
By the way, did you lost rules after each update?

**Comment by cremor** [comment]
No, I didn't loose anything for my two updates (0.2.3 to 0.3.2 and 0.3.2 to 0.3.3).

**Comment by sorz** [comment]
All requests including images and scripts will be modified on 0.3.4.

**Comment by cremor** [comment]
I can confirm that subsequent requests are now modified. But there also seems to be a regression because the main request (for the HTML page) isn't modified any more. This can again be seen on https://www.chargeprice.app with the rule "*.chargeprice.app"

**Comment by sorz** [comment]
Hope it all work now…

**Comment by cremor** [comment]
Version 0.3.5 now seems to send all requests correctly, thanks.
https://www.chargeprice.app still doesn't switch the language, but I'm not sure if that even worked before. So I'll say that this is fixed now.
