### ISSUE TITLE
Annoying red dot under Extension icon

### ISSUE THREAD

**Issue by duguyipiao** [sorz/accept-language-per-site#13]
A red dot appears under the Extension icon, when I'm visiting a website that is not in the addon's rule list. It says "Permission needed to read and change data". I wonder whether it is possible to get rid of this annoying red dot without granting permissions for accessing all websites.

**Comment by sorz** [comment]
Seems cannot be fixed without update on Firefox side. Waiting [bug 1851083](https://bugzilla.mozilla.org/show_bug.cgi?id=1851083) to be resolved.

**Comment by duguyipiao** [comment]
A (non-prefect) workaround shown in the above link: https://bugzilla.mozilla.org/show_bug.cgi?id=1851083#c21

**Comment by duguyipiao** [comment]
> Seems cannot be fixed without update on Firefox side. Waiting [bug 1851083](https://bugzilla.mozilla.org/show_bug.cgi?id=1851083) to be resolved.

The bug is fixed on firefox 129, but I still see the red dot.

**Comment by duguyipiao** [comment]
Thanks for the updating, but the red dot is still there for me with the latest version 0.4 on firefox 129.

**Comment by sorz** [comment]
Thanks for your reminder & testing! 

I tested it on Firefox 130b4 only when I did the update. I can now confirm that the red dot is still in there on 128 & 129.

It turns out the fix was done on [bug 1905931](https://bugzilla.mozilla.org/show_bug.cgi?id=1905931) actually. So the red dot will disappear on 130 and later.
